# Forest Plus Unlock Configuration
# 适用于 Quantumult X

[mitm]
hostname = forest-api.upwardsware.com, forest-china.upwardsware.com

[rewrite_local]
^https?:\/\/forest(-(api|china))?\.upwardsware\.com\/api\/v1\/users\/\d+ url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/forest.js
