hostname = forest-api.upwardsware.com, forest-china.upwardsware.com

^https?:\/\/forest(-(api|china))?\.upwardsware\.com\/api\/v1\/users\/\d+ url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/forest.js
