hostname = forest-api.upwardsware.com, forest-china.upwardsware.com, forest-trial-paywall.seekrtech.com

# 使用通用匹配逻辑，确保不管是 api 还是 challenge 路径都能被拦截
^https?:\/\/forest(-(api|china))?\.upwardsware\.com\/.*users\/\d+ url script-response-body https://raw.githubusercontent.com/refusereba4/quantumultxrules/refs/heads/main/Forest.js
